services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: texagon
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    build: ./apps/api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:secret123@db:5432/texagon
      REDIS_URL: redis://redis:6379
    ports:
      - '3000:3000'
    command: bun run dev

volumes:
  db-data:
